### ISSUE TITLE
Add CITATION.cff file 

### ISSUE THREAD

**Issue by theamarks** [Seafood-Globalization-Lab/artis-model#37]
## Problem/Observation
Not clear to users how to cite model, model versions, or model branches that they might use

### Proposed Solution

- [ ]  Add a CITATION.cff file to the root directory that will populate a citation section in the right hand side bar
- [ ]  Add note to explain that adjusting the URL or branch or commit hash when appropriate
- [ ] File could be automatically be updated when new released.

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Lisa"
  given-names: "Mona"
  orcid: "https://orcid.org/0000-0000-0000-0000"
- family-names: "Bot"
  given-names: "Hew"
  orcid: "https://orcid.org/0000-0000-0000-0000"
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2017-12-18
url: "https://github.com/github-linguist/linguist"
```

### Alternatives Considered
DOI badge, but not that clear
